import { Song } from './song';

export const SONGS: Song[] = [
    //Animals as Leaders
    // Weightless
    { title: 'An Infinite Regression', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 1, endTime: 207, videoID: '_EjVmT-D3KM' },
    { title: 'Odessa', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 207, endTime: 461, videoID: '_EjVmT-D3KM' },
    { title: 'Somnarium', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 461, endTime: 718, videoID: '_EjVmT-D3KM' },
    { title: 'Earth Departure', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 718, endTime: 1028, videoID: '_EjVmT-D3KM' },
    { title: 'Isolated Incidents', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 1028, endTime: 1256, videoID: '_EjVmT-D3KM' },
    { title: 'Do Not Go Gently', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 1256, endTime: 1477, videoID: '_EjVmT-D3KM' },
    { title: 'New Eden', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 1477, endTime: 1639, videoID: '_EjVmT-D3KM' },
    { title: 'Cylindrical Sea', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 1639, endTime: 1913, videoID: '_EjVmT-D3KM' },
    { title: 'Espera', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 1913, endTime: 2045, videoID: '_EjVmT-D3KM' },
    { title: 'To Lead You To an Overwhelming Question', artist: 'Animals as Leaders', genre: 'Instrumental Progressive Metal', album: 'Weightless', startTime: 2045, endTime: 2337, videoID: '_EjVmT-D3KM' },
    { title: 'Weightless', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 2337, endTime: 2653, videoID: '_EjVmT-D3KM' },
    { title: 'David', artist: 'Animals as Leaders', album: 'Weightless', genre: 'Instrumental Progressive Metal', startTime: 2653, endTime: 2802, videoID: '_EjVmT-D3KM' },

    //Audioslave
    //  Audioslave
    { title: 'Cochise', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 1, endTime: 222, videoID: 'eCE2cjdnTl8' },
    { title: 'Show Me How to Live', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 222, endTime: 498, videoID: 'eCE2cjdnTl8' },
    { title: 'Gasoline', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 498, endTime: 776, videoID: 'eCE2cjdnTl8' },
    { title: 'What You Are', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 776, endTime: 1024, videoID: 'eCE2cjdnTl8' },
    { title: 'Like a Stone', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 1024, endTime: 1316, videoID: 'eCE2cjdnTl8' },
    { title: 'Set It Off', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 1316, endTime: 1578, videoID: 'eCE2cjdnTl8' },
    { title: 'Shadow of the Sun', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 1578, endTime: 1920, videoID: 'eCE2cjdnTl8' },
    { title: 'I Am the Highway', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 1920, endTime: 2254, videoID: 'eCE2cjdnTl8' },
    { title: 'Exploder', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 2254, endTime: 2459, videoID: 'eCE2cjdnTl8' },
    { title: 'Hypnotize', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 2459, endTime: 2664, videoID: 'eCE2cjdnTl8' },
    { title: 'Bring Em Back Alive', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 2664, endTime: 2994, videoID: 'eCE2cjdnTl8' },
    { title: 'Light My Way', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 2994, endTime: 3309, videoID: 'eCE2cjdnTl8' },
    { title: 'Getaway Car', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 3309, endTime: 3592, videoID: 'eCE2cjdnTl8' },
    { title: 'The Last Remaining Light', artist: 'Audioslave', album: 'Audioslave', genre: 'Rock', startTime: 3592, endTime: 3927, videoID: 'eCE2cjdnTl8' },

    //The Black Dahlia Murder
    //  Nightbringers
    { title: 'Widowmaker', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 1, endTime: 201, videoID: 'VEhjvaFVrak' },
    { title: 'Of God and Serpent, Of Spectre and Snake', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 201, endTime: 430, videoID: 'VEhjvaFVrak' },
    { title: 'Matriarch', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 430, endTime: 634, videoID: 'VEhjvaFVrak' },
    { title: 'Nightbringers', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 634, endTime: 850, videoID: 'VEhjvaFVrak' },
    { title: 'Jars', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 850, endTime: 1067, videoID: 'VEhjvaFVrak' },
    { title: 'Kings of the Nightworld', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 1067, endTime: 1260, videoID: 'VEhjvaFVrak' },
    { title: 'Catacomb Hecatomb', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 1260, endTime: 1478, videoID: 'VEhjvaFVrak' },
    { title: 'As Good as Dead', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 1478, endTime: 1693, videoID: 'VEhjvaFVrak' },
    { title: 'The Lonely Deceased', artist: 'The Black Dahlia Murder', album: 'Nightbringers', genre: 'Melodic Death Metal', startTime: 1693, endTime: 1999, videoID: 'VEhjvaFVrak' },
    //  Nocturnal
    { title: 'Everything Went Black', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 1, endTime: 197, videoID: '00E6RTJh2Ro' },
    { title: 'What a Horrible Night To Have a Curse', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 197, endTime: 427, videoID: '00E6RTJh2Ro' },
    { title: 'Virally Yours', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 427, endTime: 610, videoID: '00E6RTJh2Ro' },
    { title: 'I Worship Only What You Bleed', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 610, endTime: 729, videoID: '00E6RTJh2Ro' },
    { title: 'Nocturnal', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 729, endTime: 923, videoID: '00E6RTJh2Ro' },
    { title: 'Deathmask Divine', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 923, endTime: 1140, videoID: '00E6RTJh2Ro' },
    { title: 'Of Darkness Spawned', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 1140, endTime: 1342, videoID: '00E6RTJh2Ro' },
    { title: 'Climactic Degradation', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 1342, endTime: 1501, videoID: '00E6RTJh2Ro' },
    { title: 'To a Breathless Oblivion', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 1501, endTime: 1798, videoID: '00E6RTJh2Ro' },
    { title: 'Warborn', artist: 'The Black Dahlia Murder', album: 'Nocturnal', genre: 'Melodic Death Metal', startTime: 1798, endTime: 2078, videoID: '00E6RTJh2Ro' },

    //David Maxim Micic
    //  Who Bit the Moon
    { title: 'Milk Tooth', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 1, endTime: 108, videoID: '1oiFhYl7kLM' },
    { title: 'Someone Else\'s Hat', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 108, endTime: 480, videoID: '1oiFhYl7kLM' },
    { title: 'Living Room', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 480, endTime: 781, videoID: '1oiFhYl7kLM' },
    { title: 'Beaver Moon', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 781, endTime: 841, videoID: '1oiFhYl7kLM' },
    { title: '687 Days', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 841, endTime: 1160, videoID: '1oiFhYl7kLM' },
    { title: 'Damar', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 1160, endTime: 1508, videoID: '1oiFhYl7kLM' },
    { title: 'Nobody\'s Perfect', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 1508, endTime: 1592, videoID: '1oiFhYl7kLM' },
    { title: 'When She Crafts', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 1592, endTime: 1690, videoID: '1oiFhYl7kLM' },
    { title: 'Who Bit the Moon', artist: 'David Maxim Micic', album: 'Who Bit the Moon', genre: 'Progressive Rock', startTime: 1690, endTime: 2298, videoID: '1oiFhYl7kLM' },

    //Disturbed
    //  Immortalized
    { title: 'The Eye of the Storm', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: 0, endTime: 80, videoID: 'hzNRu9sCNDk' },
    { title: 'Immortalized', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: 80, endTime: 338, videoID: 'hzNRu9sCNDk' },
    { title: 'The Vengeful One', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: '8nW-IPrzM1g' },
    { title: 'Open Your Eyes', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'LEb2ap6rELA' },
    { title: 'The Light', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'e1UUAhZ3JzM' },
    { title: 'What Are You Waiting For', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'Yvwo8f3SXKA' },
    { title: 'You\'re Mine', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'vka6wPrB4E0' },
    { title: 'Who', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'j7n9e3rtxj0' },
    { title: 'Save Our Last Goodbye', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'tcS6Dm8zXNw' },
    { title: 'Fire It Up', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'Jct3HKRYU2A' },
    { title: 'The Sound of Silence', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'u9Dg-g7t2l4' },
    { title: 'Never Wrong', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: '_EWTnmYUPpU' },
    { title: 'Who Taught You How to Hate', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: '5Hpa6MfcY8U' },
    { title: 'Tyrant', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'bUfYqkAYcE8' },
    { title: 'Legion of Monsters', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: '6dixPDujD2g' },
    { title: 'The Brave and the Bold', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: null, endTime: null, videoID: 'FP4OR8Ycipg' },
    { title: 'Warning Sign', artist: 'Disturbed', album: 'Immortalized', genre: 'Metal', startTime: 5, endTime: null, videoID: 'vuLfeDVZx8k' },

    //Gojira
    //  From Mars to Sirius
    { title: 'Ocean Planet', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 1, endTime: 333, videoID: 'kMZSJCgn_K8' },
    { title: 'Backbone', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 333, endTime: 591, videoID: 'kMZSJCgn_K8' },
    { title: 'From the Sky', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 591, endTime: 939, videoID: 'kMZSJCgn_K8' },
    { title: 'Unicorn (Instrumental)', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 939, endTime: 1068, videoID: 'kMZSJCgn_K8' },
    { title: 'Where Dragons Dwell', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 1068, endTime: 1481, videoID: 'kMZSJCgn_K8' },
    { title: 'The Heaviest Matter of the Universe', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 1481, endTime: 1719, videoID: 'kMZSJCgn_K8' },
    { title: 'Flying Whales', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 1719, endTime: 2184, videoID: 'kMZSJCgn_K8' },
    { title: 'In the Wilderness', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 2184, endTime: 2647, videoID: 'kMZSJCgn_K8' },
    { title: 'World to Come', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 2647, endTime: 3061, videoID: 'kMZSJCgn_K8' },
    { title: 'From Mars', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 3061, endTime: 3205, videoID: 'kMZSJCgn_K8' },
    { title: 'To Sirius', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 3205, endTime: 3543, videoID: 'kMZSJCgn_K8' },
    { title: 'Global Warming', artist: 'Gojira', album: 'From Mars to Sirius', genre: 'Death Metal', startTime: 3543, endTime: 4014, videoID: 'kMZSJCgn_K8' },
    //  The Link [Remastered]
    { title: 'The Link', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 1, endTime: 301, videoID: 'X71__G1hFFs' },
    { title: 'Death of Me', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 301, endTime: 648, videoID: 'X71__G1hFFs' },
    { title: 'Connected (instrumental)', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 648, endTime: 727, videoID: 'X71__G1hFFs' },
    { title: 'Remembrance', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 727, endTime: 1002, videoID: 'X71__G1hFFs' },
    { title: 'Torii (instrumental)', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 1002, endTime: 1105, videoID: 'X71__G1hFFs' },
    { title: 'Indians', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 1105, endTime: 1343, videoID: 'X71__G1hFFs' },
    { title: 'Embrace the World', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 1343, endTime: 1623, videoID: 'X71__G1hFFs' },
    { title: 'Inward Movement', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 1623, endTime: 1976, videoID: 'X71__G1hFFs' },
    { title: 'Over the Flows', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 1976, endTime: 2161, videoID: 'X71__G1hFFs' },
    { title: 'Wisdom Comes', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 2161, endTime: 2306, videoID: 'X71__G1hFFs' },
    { title: 'Dawn (instrumental)', artist: 'Gojira', album: 'The Link [Remastered]', genre: 'Death Metal', startTime: 2306, endTime: 2825, videoID: 'X71__G1hFFs' },
    //  The Way of All Flesh
    { title: 'Oroborus', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 1, endTime: 321, videoID: 'JuAb8gkxF-s' },
    { title: 'Toxic Garbage Island', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 321, endTime: 568, videoID: 'JuAb8gkxF-s' },
    { title: 'A Sight to Behold', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 568, endTime: 877, videoID: 'JuAb8gkxF-s' },
    { title: 'Yama\'s Messengers', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 877, endTime: 1122, videoID: 'JuAb8gkxF-s' },
    { title: 'The Silver Cord (instrumental)', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 1122, endTime: 1273, videoID: 'JuAb8gkxF-s' },
    { title: 'All the Tears', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 1273, endTime: 1494, videoID: 'JuAb8gkxF-s' },
    { title: 'Adoration for None (ft. Randy Blythe)', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 1494, endTime: 1873, videoID: 'JuAb8gkxF-s' },
    { title: 'The Art of Dying', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 1873, endTime: 2468, videoID: 'JuAb8gkxF-s' },
    { title: 'Esoteric Surgery', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 2468, endTime: 2813, videoID: 'JuAb8gkxF-s' },
    { title: 'Vacuity', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 2813, endTime: 3104, videoID: 'JuAb8gkxF-s' },
    { title: 'Wolf Down the Earth', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 3104, endTime: 3490, videoID: 'JuAb8gkxF-s' },
    { title: 'The Way of All Flesh', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 3490, endTime: 3910, videoID: 'JuAb8gkxF-s' },
    { title: 'Hidden Song', artist: 'Gojira', album: 'The Way of All Flesh', genre: 'Death Metal', startTime: 3910, endTime: 4094, videoID: 'JuAb8gkxF-s' },

    //Intervals
    //  The Shape of Color
    { title: 'I\'m Awake', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'OHvMYUR8SuE' },
    { title: 'Sure Shot', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: '2NADqpeFguE' },
    { title: 'Fable', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 't8RFcWCWkcI' },
    { title: 'Sweet Tooth', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'SgXZozc7nuA' },
    { title: 'Black Box', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'jLhJxRrFeqk' },
    { title: 'Slight of Hand', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'ZNZ-Lr2UFHo' },
    { title: 'Meridian', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'nmLEg7pykKE' },
    { title: 'Libra', artist: 'Intervals', album: 'The Shape of Color', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'Fx8c3CuUxw0' },
    //  The Way Forward
    { title: 'Touch and Go', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: '-Yrp2e21_Tc' },
    { title: 'Impulsively Responsible', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'piyFb0d6yAs' },
    { title: 'A Different Light', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'cZJgb-UjkcM' },
    { title: 'By Far and Away', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'BsUUG3Aq9Vc' },
    { title: 'Belvedere', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'Htw4tnmR7hU' },
    { title: 'Rubicon Artist', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: '8RsysaNCy5w' },
    { title: 'The Waterfront', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: 'sADHe4wc17E' },
    { title: 'Leave No Stone', artist: 'Intervals', album: 'The Way Forward', genre: 'Instrumental Rock', startTime: null, endTime: null, videoID: '5yUp_RooDFw' },

    //Jeff Loomis
    //  Zero Order Phase
    { title: 'Shouting Fire at a Funeral', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 1, endTime: 293, videoID: '_pDjGH8h9LI' },
    { title: 'Opulent Maelstrom', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 293, endTime: 661, videoID: '_pDjGH8h9LI' },
    { title: 'Jato Unit', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 661, endTime: 942, videoID: '_pDjGH8h9LI' },
    { title: 'Azure Haze', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 942, endTime: 1242, videoID: '_pDjGH8h9LI' },
    { title: 'Cashmere Shiv', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 1242, endTime: 1620, videoID: '_pDjGH8h9LI' },
    { title: 'Race Against Disaster', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 1620, endTime: 1993, videoID: '_pDjGH8h9LI' },
    { title: 'Sacristy', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 1993, endTime: 2283, videoID: '_pDjGH8h9LI' },
    { title: 'Devil Theory', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 2283, endTime: 2660, videoID: '_pDjGH8h9LI' },
    { title: 'Miles of Machines', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 2660, endTime: 3006, videoID: '_pDjGH8h9LI' },
    { title: 'Departure', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 3006, endTime: 3242, videoID: '_pDjGH8h9LI' },
    { title: 'Omega\'s Influence', artist: 'Jeff Loomis', album: 'Zero Order Phase', genre: 'Instrumental Thrash Metal', startTime: 3242, endTime: null, videoID: '_pDjGH8h9LI' },

    //John Petrucci
    // Suspended Animation
    { title: 'Jaws of Life', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 1, endTime: 449, videoID: 'IUj6nDs_Mqg' },
    { title: 'Glasgow Kiss', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 449, endTime: 918, videoID: 'IUj6nDs_Mqg' },
    { title: 'Tunnel Vision', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 918, endTime: 1313, videoID: 'IUj6nDs_Mqg' },
    { title: 'Wishful Thinking', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 1313, endTime: 1762, videoID: 'IUj6nDs_Mqg' },
    { title: 'Damage Control', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 1762, endTime: 2317, videoID: 'IUj6nDs_Mqg' },
    { title: 'Curve', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 2317, endTime: 2700, videoID: 'IUj6nDs_Mqg' },
    { title: 'Lost Without You', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 2700, endTime: 2996, videoID: 'IUj6nDs_Mqg' },
    { title: 'Animate-Inanimate', artist: 'John Petrucci', album: 'Suspended Animation', genre: 'Instrumental Progressive Metal', startTime: 2996, endTime: 3702, videoID: 'IUj6nDs_Mqg' },

    //Lamb of God
    //  Ashes of the Wake
    { title: 'Laid to Rest', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 1, endTime: 230, videoID: 'FNGEQmzDLR0' },
    { title: 'Hourglass', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 230, endTime: 470, videoID: 'FNGEQmzDLR0' },
    { title: 'Now You\'ve Got Something to Die For', artist: 'Lamb of God', genre: 'Groove Metal', album: 'Ashes of the Wake', startTime: 470, endTime: 690, videoID: 'FNGEQmzDLR0' },
    { title: 'The Faded Line', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 690, endTime: 967, videoID: 'FNGEQmzDLR0' },
    { title: 'Omerta', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 967, endTime: 1253, videoID: 'FNGEQmzDLR0' },
    { title: 'Blood of the Scribe', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 1253, endTime: 1516, videoID: 'FNGEQmzDLR0' },
    { title: 'One Gun', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 1516, endTime: 1755, videoID: 'FNGEQmzDLR0' },
    { title: 'Break You', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 1755, endTime: 1971, videoID: 'FNGEQmzDLR0' },
    { title: 'What I\'ve Become', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 1971, endTime: 2180, videoID: 'FNGEQmzDLR0' },
    { title: 'Ashes of the Wake', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 2180, endTime: 2527, videoID: 'FNGEQmzDLR0' },
    { title: 'Remorse Is for the Dead', artist: 'Lamb of God', album: 'Ashes of the Wake', genre: 'Groove Metal', startTime: 2527, endTime: null, videoID: 'FNGEQmzDLR0' },

    //Megadeth
    //  Dystopia
    { title: 'The Threat is Real', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: '3-d6LFLpBvw' },
    { title: 'Dystopia', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'QrV61ATP3Ec' },
    { title: 'Fatal Illusion', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: '7MRtdd3tXI4' },
    { title: 'Bullet to the Brain', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'xdEPQE5tLgQ' },
    { title: 'Post American World', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'mEkXyEIu3OU' },
    { title: 'Poisonous Shadows', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'unQZvhQ9Giw' },
    { title: 'Conquer or Die', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'dQ_-tUKT-nY' },
    { title: 'Lying in State', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'yFxsnOm2kLg' },
    { title: 'Foreign Policy', artist: 'Megadeth', album: 'Dystopia', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'xEzYIS5L-nM' },
    //  Endgame
    { title: 'Dialectic Chaos', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'iH0iduT0mGo' },
    { title: 'This Day We Fight', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: '7F3rzYfRtus' },
    { title: '44 Minutes', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'eU0LS_96cso' },
    { title: '1,320\'', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'VXnu1Q8J2Io' },
    { title: 'Bite the Hand', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'EcHz3F4O2Mw' },
    { title: 'Bodies', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'UgT0G76iPDY' },
    { title: 'Endgame', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'TX3PlxvdEf4' },
    { title: 'The Hardest Part of Letting Go... Sealed With a Kiss', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'OAghPu4sEUs' },
    { title: 'Head Crusher', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: null, endTime: null, videoID: 'XurU3TPHjzY' },
    { title: 'The Right to Go Insane', artist: 'Megadeth', album: 'Endgame', genre: 'Thrash Metal', startTime: 17, endTime: 234, videoID: 'm20sJNgZ17U' },

    //Metallica
    //  Master of Puppets
    { title: 'Battery', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 1, endTime: 309, videoID: '8PNxO_jM_ck' },
    { title: 'Master of Puppets', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 309, endTime: 824, videoID: '8PNxO_jM_ck' },
    { title: 'The Thing That Should Not Be', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 824, endTime: 1220, videoID: '8PNxO_jM_ck' },
    { title: 'Welcome Home (Sanitarium)', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 1220, endTime: 1608, videoID: '8PNxO_jM_ck' },
    { title: 'Disposable Heroes', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 1608, endTime: 2107, videoID: '8PNxO_jM_ck' },
    { title: 'Leper Messiah', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 2107, endTime: 2456, videoID: '8PNxO_jM_ck' },
    { title: 'Orion', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 2456, endTime: 2974, videoID: '8PNxO_jM_ck' },
    { title: 'Damage Inc.', artist: 'Metallica', album: 'Master of Puppets', genre: 'Thrash Metal', startTime: 2974, endTime: 3287, videoID: '8PNxO_jM_ck' },
    //  Ride the Lightning
    { title: 'Fight Fire With Fire', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 1, endTime: 280, videoID: 'OhT0g9jULpw' },
    { title: 'Ride the Lightning', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 280, endTime: 673, videoID: 'OhT0g9jULpw' },
    { title: 'For Whom the Bell Tolls', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 673, endTime: 968, videoID: 'OhT0g9jULpw' },
    { title: 'Fade to Black', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 968, endTime: 1376, videoID: 'OhT0g9jULpw' },
    { title: 'Trapped Under Ice', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 1376, endTime: 1617, videoID: 'OhT0g9jULpw' },
    { title: 'Escape', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 1617, endTime: 1879, videoID: 'OhT0g9jULpw' },
    { title: 'Creeping Death', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 1879, endTime: 2274, videoID: 'OhT0g9jULpw' },
    { title: 'The Call of Ktulu', artist: 'Metallica', album: 'Ride the Lightning', genre: 'Thrash Metal', startTime: 2274, endTime: 2811, videoID: 'OhT0g9jULpw' },

    //Nick Johnston
    //  Remarkable Human
    { title: 'Ignore Alien Orders', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 1, endTime: 228, videoID: 'fYfe_JkVsDo' },
    { title: 'Remarkably Human', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 228, endTime: 627, videoID: 'fYfe_JkVsDo' },
    { title: 'Impossible Things', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 627, endTime: 1060, videoID: 'fYfe_JkVsDo' },
    { title: 'Poison Touch', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 1060, endTime: 1325, videoID: 'fYfe_JkVsDo' },
    { title: 'Hypergiant', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 1325, endTime: 1778, videoID: 'fYfe_JkVsDo' },
    { title: 'Weakened By Winter', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 1778, endTime: 2256, videoID: 'fYfe_JkVsDo' },
    { title: 'Fear Had Him By The Throat', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 2256, endTime: 2598, videoID: 'fYfe_JkVsDo' },
    { title: 'A Sick and Injured Brain', artist: 'Nick Johnston', album: 'Remarkably Human', genre: 'Instrumental Rock', startTime: 2598, endTime: 3164, videoID: 'fYfe_JkVsDo' },

    //Plini
    //  Handmade Cities
    { title: 'Electric Sunrise', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 1, endTime: 310, videoID: 'Yk6OQ9IF4Xg' },
    { title: 'Handmade Cities', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 310, endTime: 595, videoID: 'Yk6OQ9IF4Xg' },
    { title: 'Inhale', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 595, endTime: 894, videoID: 'Yk6OQ9IF4Xg' },
    { title: 'Every Piece Matters', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 894, endTime: 1114, videoID: 'Yk6OQ9IF4Xg' },
    { title: 'Pastures', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 1114, endTime: 1688, videoID: 'Yk6OQ9IF4Xg' },
    { title: 'Here We Are Again', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 1568, endTime: 1726, videoID: 'Yk6OQ9IF4Xg' },
    { title: 'Cascade', artist: 'Plini', album: 'Handmade Cities', genre: 'Instrumental Progressive Rock', startTime: 1726, endTime: 2086, videoID: 'Yk6OQ9IF4Xg' },

    //Polyphia
    // Renaissance
    { title: 'Culture Shock', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 1, endTime: 282, videoID: 'Q2dfe2yseIM' },
    { title: 'Light', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 282, endTime: 512, videoID: 'Q2dfe2yseIM' },
    { title: 'Florence', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 512, endTime: 703, videoID: 'Q2dfe2yseIM' },
    { title: 'Nightmare', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 703, endTime: 948, videoID: 'Q2dfe2yseIM' },
    { title: 'Storm', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 948, endTime: 1158, videoID: 'Q2dfe2yseIM' },
    { title: 'Bittersweet', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 1158, endTime: 1392, videoID: 'Q2dfe2yseIM' },
    { title: 'Symmetry', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 1392, endTime: 1509, videoID: 'Q2dfe2yseIM' },
    { title: 'Ivory', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 1509, endTime: 1695, videoID: 'Q2dfe2yseIM' },
    { title: 'Paradise', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 1695, endTime: 1952, videoID: 'Q2dfe2yseIM' },
    { title: 'Amour', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 1952, endTime: 2173, videoID: 'Q2dfe2yseIM' },
    { title: 'Crush', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 2173, endTime: 2414, videoID: 'Q2dfe2yseIM' },
    { title: 'Euphoria', artist: 'Polyphia', album: 'Renaissance', genre: 'Instrumental Progressive Metal', startTime: 2414, endTime: 2670, videoID: 'Q2dfe2yseIM' },

    //Sithu Aye
    //  Set Course for Andromeda
    { title: 'Space Cadet', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 1, endTime: 113, videoID: 'mQsAmJUCcg4-s' },
    { title: 'Set Course for Andromeda!!!', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 113, endTime: 631, videoID: 'mQsAmJUCcg4-s' },
    { title: 'Constants and Variables', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 631, endTime: 1139, videoID: 'mQsAmJUCcg4-s' },
    { title: 'Spiral', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 1139, endTime: 1399, videoID: 'mQsAmJUCcg4-s' },
    { title: 'Beyond the Boundary', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 1399, endTime: 1913, videoID: 'mQsAmJUCcg4-s' },
    { title: 'Transient Transistors', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 1913, endTime: 2389, videoID: 'mQsAmJUCcg4-s' },
    { title: '...We Actually Made it to Andromeda!!!', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 2389, endTime: 2766, videoID: 'mQsAmJUCcg4-s' },
    { title: 'The Andromedan Pt 1: A Single Step', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 2766, endTime: 3088, videoID: 'mQsAmJUCcg4-s' },
    { title: 'The Andromedan Pt 2: Mystic Village', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 3088, endTime: 3480, videoID: 'mQsAmJUCcg4-s' },
    { title: 'The Andromedan Pt 3: Trials of the Elements', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 3480, endTime: 3725, videoID: 'mQsAmJUCcg4-s' },
    { title: 'The Andromedan Pt 4: The Darkness Within', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 3725, endTime: 3884, videoID: 'mQsAmJUCcg4-s' },
    { title: 'The Andromedan Pt 5: Rebirth', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 3884, endTime: 4255, videoID: 'mQsAmJUCcg4-s' },
    { title: 'The Andromedan Pt 6: Mother of Creation', artist: 'Sithu Aye', album: 'Set Course for Andromeda', genre: 'Instrumental Progressive Metal', startTime: 4255, endTime: 4509, videoID: 'mQsAmJUCcg4-s' },

    //Tremonti
    //  Cauterize
    { title: 'Radical Change', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 1, endTime: 263, videoID: 'uEFEPTxn8B8' },
    { title: 'Flying Monkeys', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 263, endTime: 548, videoID: 'uEFEPTxn8B8' },
    { title: 'Cauterize', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 548, endTime: 798, videoID: 'uEFEPTxn8B8' },
    { title: 'Arm Yourself', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 798, endTime: 1014, videoID: 'uEFEPTxn8B8' },
    { title: 'Dark Trip', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 1014, endTime: 1308, videoID: 'uEFEPTxn8B8' },
    { title: 'Another Heart', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 1308, endTime: 1545, videoID: 'uEFEPTxn8B8' },
    { title: 'Fall Again', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 1545, endTime: 1833, videoID: 'uEFEPTxn8B8' },
    { title: 'Tie the Noose', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 1833, endTime: 2043, videoID: 'uEFEPTxn8B8' },
    { title: 'Sympathy', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 2043, endTime: 2303, videoID: 'uEFEPTxn8B8' },
    { title: 'Providence', artist: 'Tremonti', album: 'Cauterize', genre: 'Metal', startTime: 2303, endTime: 2648, videoID: 'uEFEPTxn8B8' },

    //Various
    //  It Came from the 80\'s - Vol 2
    { title: 'It Came from the 80\'s - Vol 2 (Full Mix)', artist: 'Various Artists', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: null, endTime: null, videoID: 'NyfL9LC1DC4' },
    { title: 'Wave Rider', artist: 'Isidor', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 1, endTime: 219, videoID: 'NyfL9LC1DC4' },
    { title: 'Crimewave 2', artist: 'Mega Drive', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 219, endTime: 400, videoID: 'NyfL9LC1DC4' },
    { title: 'Launch Disintegration', artist: 'Tonebox', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 400, endTime: 712, videoID: 'NyfL9LC1DC4' },
    { title: 'Occult', artist: 'ALEX', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 712, endTime: 937, videoID: 'NyfL9LC1DC4' },
    { title: 'Celestial Breakdown', artist: 'Tonebox', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 937, endTime: 1008, videoID: 'NyfL9LC1DC4' },
    { title: 'Cyborg Chase', artist: 'Toxxify', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 1008, endTime: 1147, videoID: 'NyfL9LC1DC4' },
    { title: 'Phantom Planet', artist: 'Nightcrawler', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 1147, endTime: 1393, videoID: 'NyfL9LC1DC4' },
    { title: 'Soul Siphon', artist: 'Daniel Deluxe', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 1393, endTime: 1557, videoID: 'NyfL9LC1DC4' },
    { title: 'Futurehell', artist: 'DevilRazor', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 1557, endTime: 1700, videoID: 'NyfL9LC1DC4' },
    { title: 'Trick R Treat', artist: 'Raydar', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 1700, endTime: 2156, videoID: 'NyfL9LC1DC4' },
    { title: 'Face Me', artist: 'Ace Buchannon', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 2156, endTime: 2342, videoID: 'NyfL9LC1DC4' },
    { title: 'Machine Uprising', artist: 'ABIIIISMO', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 2342, endTime: 2555, videoID: 'NyfL9LC1DC4' },
    { title: 'Electrocutioner', artist: 'Arcade Summer', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 2555, endTime: 2765, videoID: 'NyfL9LC1DC4' },
    { title: 'Phantasm Theme', artist: 'Nightcrawler', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 2765, endTime: 2891, videoID: 'NyfL9LC1DC4' },
    { title: 'Screams & Whispers', artist: 'Dance with the Dead', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 2891, endTime: 3170, videoID: 'NyfL9LC1DC4' },
    { title: 'Elevn', artist: 'Escape the Matter', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 3170, endTime: 3428, videoID: 'NyfL9LC1DC4' },
    { title: 'Elevn (Remix)', artist: 'The Fog', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 3428, endTime: 3634, videoID: 'NyfL9LC1DC4' },
    { title: 'Riot', artist: 'Dance with the Dead', album: 'It Came from the 80\'s - Vol 2', genre: 'Retro Darkwave', startTime: 3634, endTime: 3811, videoID: 'NyfL9LC1DC4' },
    //  It Came from the 80\'s - Vol 5
    { title: 'It Came from the 80\'s - Vol 5 (Full Mix)', artist: 'Various Artists', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: null, endTime: null, videoID: 'bnefm57d7z4' },
    { title: 'Sacrifice (Daniel Deluxe Remix)', artist: 'Tokyo Rose', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 1, endTime: 261, videoID: 'bnefm57d7z4' },
    { title: 'The Chase', artist: 'Tonebox', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 261, endTime: 447, videoID: 'bnefm57d7z4' },
    { title: 'Geist', artist: 'Mega Drive', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 447, endTime: 680, videoID: 'bnefm57d7z4' },
    { title: 'Midnight Terror', artist: 'Ethan Red', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 680, endTime: 919, videoID: 'bnefm57d7z4' },
    { title: 'Black Magic', artist: 'ALEX', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 919, endTime: 1042, videoID: 'bnefm57d7z4' },
    { title: 'Blood Oath Feat. WVLFPAKT', artist: 'Tokyo Rose', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 1042, endTime: 1153, videoID: 'bnefm57d7z4' },
    { title: 'That Fucking Nobody is John Wick', artist: 'Maximum Overdrive', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 1153, endTime: 1368, videoID: 'bnefm57d7z4' },
    { title: 'Mega Nova', artist: 'Justin Geer', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 1368, endTime: 1627, videoID: 'bnefm57d7z4' },
    { title: 'Alien Attack #2', artist: 'Johnny Ola', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 1627, endTime: 1815, videoID: 'bnefm57d7z4' },
    { title: 'Leather Apron', artist: 'POLYTÆM', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 1815, endTime: 2014, videoID: 'bnefm57d7z4' },
    { title: 'NATHAN DANDY', artist: 'NATHAN DANDY', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2014, endTime: 2217, videoID: 'bnefm57d7z4' },
    { title: 'Occult II', artist: 'ALEX ', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2217, endTime: 2292, videoID: 'bnefm57d7z4' },
    { title: 'Ragnarok', artist: 'The Outrider', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2292, endTime: 2457, videoID: 'bnefm57d7z4' },
    { title: 'Dream Hacker', artist: 'Solar Storm', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2457, endTime: 2658, videoID: 'bnefm57d7z4' },
    { title: 'Hyper Alloy', artist: 'Grave Slayer', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2658, endTime: 2810, videoID: 'bnefm57d7z4' },
    { title: 'Star Eater (Starfounder Remix)', artist: 'Daniel Deluxe', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2810, endTime: 2978, videoID: 'bnefm57d7z4' },
    { title: 'Suspiria', artist: 'Super Awesome', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 2978, endTime: 3184, videoID: 'bnefm57d7z4' },
    { title: 'The Exorcism Theme (Re-Work)', artist: 'The Starfighter', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 3184, endTime: 3324, videoID: 'bnefm57d7z4' },
    { title: 'Cyber War', artist: 'Garth Knight', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 3324, endTime: 3542, videoID: 'bnefm57d7z4' },
    { title: 'Garbage Day', artist: 'Slvmber', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 3542, endTime: 3614, videoID: 'bnefm57d7z4' },
    { title: 'Masked Death', artist: 'Volkor X', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 3614, endTime: 3955, videoID: 'bnefm57d7z4' },
    { title: 'Skeletons in the Attic', artist: 'Dance with the Dead', album: 'It Came from the 80\'s - Vol 5', genre: 'Retro Darkwave', startTime: 3955, endTime: 4216, videoID: 'bnefm57d7z4' },
    
    //Periphery Mix
    { title: 'Letter Experiment', artist: 'Periphery', album: 'P1', genre: 'Progressive Metal', startTime: 1, endTime: 411, videoID: '4luh8j8AQbU' },
    { title: 'All New Materials', artist: 'Periphery', album: 'P1', genre: 'Progressive Metal', startTime: 1, endTime: 321, videoID: '6GfIoi9eG0A' },
    { title: 'Buttersnips', artist: 'Periphery', album: 'P1', genre: 'Progressive Metal', startTime: 1, endTime: 354, videoID: '4ZjEwB-fx3Q' },
    { title: 'Zyglrox', artist: 'Periphery', album: 'P1', genre: 'Progressive Metal', startTime: 1, endTime: 307, videoID: 'TiwzdGjskwc' },
    { title: 'Racecar', artist: 'Periphery', album: 'P1', genre: 'Progressive Metal', startTime: 1, endTime: 921, videoID: 'OZwCQrxceaI' },
    { title: 'Have A Blast', artist: 'Periphery', album: 'P2', genre: 'Progressive Metal', startTime: 1, endTime: 356, videoID: 'L6c8Cl3Hka0' },
    { title: 'Scarlet', artist: 'Periphery', album: 'P2', genre: 'Progressive Metal', startTime: 1, endTime: 248, videoID: 'pWtKpoRYJV8' },
    { title: 'Luck As A Constant', artist: 'Periphery', album: 'P2', genre: 'Progressive Metal', startTime: 1, endTime: 364, videoID: 'G8nM0LTxTOo' },
    { title: 'Erised', artist: 'Periphery', album: 'P2', genre: 'Progressive Metal', startTime: 1, endTime: 373, videoID: 'khACKq23bC8' },
    { title: 'Mile Zero', artist: 'Periphery', album: 'P2', genre: 'Progressive Metal', startTime: 1, endTime: 331, videoID: 'dz3E_JNW4oU' },
    { title: 'Marigold', artist: 'Periphery', album: 'P3', genre: 'Progressive Metal', startTime: 1, endTime: 331, videoID: 'rmtU2WJfPgU' },
    { title: 'The Way The News Goes...', artist: 'Periphery', album: 'P3', genre: 'Progressive Metal', startTime: 1, endTime: 303, videoID: 'pGLuKRVX-J4' },
    { title: 'Absolomb', artist: 'Periphery', album: 'P3', genre: 'Progressive Metal', startTime: 1, endTime: 463, videoID: 'gdP3O8L_MV4' },
    { title: 'Prayer Position', artist: 'Periphery', album: 'P3', genre: 'Progressive Metal', startTime: 1, endTime: 276, videoID: '91eAE7GMBBk' },
    { title: 'Captain On', artist: 'Periphery', album: 'Icarus EP', genre: 'Progressive Metal', startTime: 1, endTime: 191, videoID: '3jkaUUzugdY' },
    { title: 'Eureka!', artist: 'Periphery', album: 'Icarus EP', genre: 'Progressive Metal', startTime: 1, endTime: 316, videoID: '62D2d7ZWyxA' },
    { title: 'The Summer Jam', artist: 'Periphery', album: 'Clear EP', genre: 'Progressive Metal', startTime: 1, endTime: 257, videoID: 'fOtinnFWp7Q' },
    { title: 'Zero', artist: 'Periphery', album: 'Clear EP', genre: 'Progressive Metal', startTime: 1, endTime: 330, videoID: 'ZhihLzDcdIs' },
    { title: 'Passenger', artist: 'Periphery', album: 'Single', genre: 'Progressive Metal', startTime: 1, endTime: 215, videoID: 'W3Ct_Yg5CuM' }
];
